project_id = "jplhtputzixwqarqlrth"

[functions.admin-reset-password]
verify_jwt = false

[functions.employee-auth]
verify_jwt = false

[functions.employee-chat]
verify_jwt = false

[functions.external-api]
verify_jwt = false
